apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-frontend
  namespace: moviez
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-frontend
  template:
    metadata:
      labels:
        app: movie-frontend
    spec:
      containers:
        - name: frontend
          image: public.ecr.aws/p3h2q3u4/moviez/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              value: "http://movie-backend:5000"
