apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviez-app
  namespace: moviez
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviez
  template:
    metadata:
      labels:
        app: moviez
    spec:
      containers:
        - name: backend
          image: public.ecr.aws/p3h2q3u4/moviez/backend:latest
          ports:
            - containerPort: 5000

        - name: frontend
          image: public.ecr.aws/p3h2q3u4/moviez/frontend:latest
          ports:
            - containerPort: 80
