apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moviez-ingress
  namespace: moviez
spec:
  ingressClassName: traefik
  rules:
    - host: moviezlist.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moviez-service
                port:
                  number: 80
