apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: moviez-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.31.47.200-172.31.47.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: moviez-adv
  namespace: metallb-system
