apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-backend
  namespace: moviez
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-backend
  template:
    metadata:
      labels:
        app: movie-backend
    spec:
      containers:
        - name: backend
          image: public.ecr.aws/p3h2q3u4/moviez/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
